
#' Automobile Power Generation
#'
#' This function determines the power generated by a given flow rate for a reservoir
#' 
#' @param crolling rolling resistive coefficient (0.015)
#' @param cdrag aerodynamic resistive coefficient (0.3)
#' @param m mass of truck (kg)
#' @param V vehicle speed (assuming no headwind) in m/s (or mps) m: is vehicle mass in kg
#' @param A surface area of car (m^2)
#' @param g acceleration due to gravity (m/s) default=9.8
#' @param p_air density of air (1.2kg/m^3)
#' @return Pb (W)
#'
# function definition
automobile_power_generation = function(crolling=0.015, m, cdrag=0.3, V, A, g=9.8, p_air=1.2) {
  # here's were I calculate power
  Pb = crolling * m * g * V + (0.5 * A * p_air * cdrag * V^3)
  return(Pb)
}
